### ISSUE TITLE
Problem in submitting application

### ISSUE THREAD

**Issue by mizanul** [zrdev/zrdev.github.io#54] opened 2014-07-10 15:04 UTC
User get consistently the following message:
"The server did not respond. Please check your Internet connection and
try again.If this problem persists for more than a few minutes, please
contact us at zerorobotics@mit.edu."

**Comment by dddoss** [comment] 2014-07-10 15:14
Duplicate of #49 I think. Definitely high-priority though.

**Closed as completed** 2014-07-10 17:12 UTC
Labels: high-priority
