### ISSUE TITLE
Revision Control

### ISSUE THREAD

**Issue by avivasiegel** [zrdev/zrdev.github.io#69] opened 2014-08-28 14:40 UTC
Is it possible to re-add revision control to the IDE?

**Comment by avivasiegel** [comment] 2014-08-28 14:44
What about the idea of adding upload capability, so people can use local version control software?

**Comment by mizanul** [comment] 2014-08-28 15:06
Yes, it might be possible.  I have to investigate and research to find out the best way to implement version control on IDE.  Since we are hosting all projects on the Google Drive, maybe it is possible through Google.

**Comment by mizanul** [comment] 2015-01-15 21:40
Duplicate of #70

**Closed as completed** 2015-01-15 21:40 UTC
Labels: enhancement
