### ISSUE TITLE
escaping issue in the visualization

### ISSUE THREAD

**Issue by mizanul** [zrdev/zrdev.github.io#75] opened 2014-09-18 14:50 UTC
From Rich
"You will want to check your debug statements for single quotes ( ' ).. The
rest of the details are that our simulations did run, but the visualization
couldn't display them. I suspect that the ' marks come down in the json data
and throw the visualizer off. There is probably an escaping issue here. "

**Comment by alvarso** [comment] 2015-06-29 21:59
Duplicate of #58.

**Closed as completed by alvarso** 2015-06-29 21:59 UTC
Labels: duplicate
