### ISSUE TITLE
High-school registration returns "Server Did Not Respond" error

### ISSUE THREAD

**Issue by dddoss** [zrdev/zrdev.github.io#49] opened 2014-07-07 15:35 UTC
"The server did not respond. Please check your Internet connection and try again.If this problem persists for more than a few minutes, please contact us at zerorobotics@mit.edu."

From javascript console:

POST http://zrdev.elasticbeanstalk.com/applicationresource/add/ 404 (Not Found) angular.js:8165
(anonymous function) angular.js:8165
sendReq angular.js:7967
$http.serverRequest angular.js:7708
wrappedCallback angular.js:11100
(anonymous function) angular.js:11186
Scope.$eval angular.js:12175
Scope.$digest angular.js:12004
Scope.$apply angular.js:12279
(anonymous function) angular.js:18332
(anonymous function) angular.js:2716
forEach angular.js:330
eventHandler angular.js:2715

**Comment by mizanul** [comment] 2014-07-10 17:13
It looks like the problem is in QA environment.

**Comment by mizanul** [comment] 2014-07-20 01:54
The fix has been deployed in QA.

**Comment by ghost** [comment] 2014-07-22 01:43
Not a problem in Python implementation. Reopen this if we go back to Java

**Closed as completed by ghost** 2014-07-22 01:43 UTC
Labels: high-priority
